# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  image: 'booking'
  latestTag: '$(image):latest'

steps:
- script: |
    docker build -f ./Dockerfile -t $(DockerId).azurecr.io/$(latestTag) .
    docker login -u $(DockerId) -p $(pswd) $(Dockerid).azurecr.io
    docker push $(dockerId).azurecr.io/$(latestTag)
  displayName: 'Build and push Docker image'
