version: '3.7' #Version 3.5 or above.
services: 
  booking:
    container_name: booking
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4001:4001

    networks: 
      - frontend
      # ...

networks: 
  # ...
  frontend:
  # The following line ensures the full name of the network will be 'frontend'
    name: frontend